### ISSUE TITLE
the selection of cut-off thresholds during network construction

### ISSUE THREAD

**Issue by weibokong27** [Mengting-Maggie-Yuan/warming-network-complexity-stability#1]
Dear Professor Yuan, 

it’s a great honor to read this paper you published in Nature Climate Change.

I am confused about the selection of cut-off thresholds during network construction: If there are more networks built, the default optimal threshold of each network is quite different (for example, 0.7-0.9), are these networks still comparable? 

But if the same threshold is set for all network, does it make sense to build a network based on random matrix theory (RMT)?

Looking forward to your reply, thank you！

BEST WISHES！

**Comment by Mengting-Maggie-Yuan** [comment]
Hello! Looks like the data structures/community compositions are quite different for your datasets so the RMT thresholds vary. Some datasets contain more noise and some have less.
RMT is one way to determine a cutoff to separate noise from systematic signals. These very different thresholds themselves contain valuable information regarding these datasets.
Another way would be to use a single cutoff value within the range of RMT-determined ones for all datasets (for example, the average of all the cutoffs, or mid-point of the range). This way there is one cutoff that is reasonably close to the optimal thresholds of all datasets.
I don't know of a standard way to compare different networks. But whichever method is chosen, the networks should be interpreted accordingly.
Hope this helps!

Best,
Maggie Yuan
