### ISSUE TITLE
Error in using FigS1ab.find_env_links.py

### ISSUE THREAD

**Issue by Kaoping** [Mengting-Maggie-Yuan/warming-network-complexity-stability#2]
Hi Maggie,

I am trying to using you code "FigS1ab.find_env_links.py", but when I run the code in python3 env, there is an error message "Traceback (most recent call last):
  File "FigS1ab.find_env_links.py", line 179, in <module>
    main()
  File "FigS1ab.find_env_links.py", line 160, in main
    samples_otu, otu_ids, otu_abunds = read_otus(args['otu_path'], node_wt_edge)
  File "FigS1ab.find_env_links.py", line 70, in read_otus
    otu_abunds_np = np.array(otu_abunds)[:,np_order]
IndexError: index 24 is out of bounds for axis 1 with size 24"
Could you help me to fix this error? Thank you very much.

Best,
Kaoping

**Comment by Mengting-Maggie-Yuan** [comment]
Thanks for raising the question, Kaoping.
The bug is fixed now.

**Comment by Kaoping** [comment]
Thanks for your help.
